Add rate-limiter
shazow/ethspam pull request #7
Opened 2020-04-01 11:16 UTC by rjl493456442

Hi @shazow, thanks for the great tool. Here is a PR for a few improvements.

First, it adds the rate limiter for request generation. The tool will generate RPC calls without any limitation by default. However, in some cases, the rate limiter can help a lot. E.g. generate some workload but not for benchmark.

Second, it fixes an issue when adding new clues from a real chain. Normally in some testnets, some blocks can be empty. It doesn't make sense to refresh the "generator state" without new clues added.
Especially the state is retrieved for the first time, it will lead to some invalid RPC generated.

2020-04-01 13:29 UTC, shazow requested changes
Hiya, thank you for this! Looks great, one minor change request.

Also could you share how you're using ethspam that you require rate limiting? I generally imagined it being rate limiting by backpressure from the pipe consumer.

2020-04-01 13:29 UTC, shazow commented on main.go
> +		rlimit.Wait(context.Background()) // Waiting a bucket token
Any idea if this adds any overhead when no limiter is set? Might be safer to have a nil *Limiter when it's not set?

2020-04-02 02:33 UTC, rjl493456442 commented
@shazow Updated.

I want to use `ethspam` to generate some simulation workload for light client but not for benchmarking purpose. Some real workload is enough to test whether light client works correctly or not.

2020-04-02 17:44 UTC, shazow approved these changes
I think this is good enough for now, thank you!

> I want to use ethspam to generate some simulation workload for light client but not for benchmarking purpose. Some real workload is enough to test whether light client works correctly or not.

Could you expand on how you're actually using it, just so I can keep it in mind? Like, what's the full command you're running with ethspam?

2020-04-02 17:44 UTC, shazow commented on main.go
> +					time.Sleep(time.Second * 5)
Just noticed, this will block the `ctx.Done()` which could be annoying.

2020-04-03 09:06 UTC, rjl493456442 commented
@shazow the command I used is `ethspam -r 0.5 --rpc ENDPOINT | versus ENDPOINT`. Basically generate meaningful workload to make light clients running.

2020-04-03 13:54 UTC, shazow commented
But versus does the rate limiting, no? Why do you need ratelimiting from ethspam? rate-limiting ethspam with versus will produce invalid results (because versus assumes the input is unthrottled for accurate measuremnet).

2020-04-04 13:08 UTC, rjl493456442 commented
I've just skimmed the versus code, but I didn't find any rate-limiting thing. 

Regarding the benchmarking report, I think the rate-limiting shouldn't affect the correctness. For example, `RPS` is calculated by `total_requests_made/duration`, I don't get why it will generate some invalid results. (Probably I miss something :P).

The rate-limiting will affect that if user specifies `stop-after=1m`, then less requests will be made. But I guess it should be okish.

2020-04-04 17:07 UTC, shazow commented
Er I meant more that versus already does other kinds of flow control, and relies on ethspam being unbounded itself. Would it make more sense to add a maximum consumption rate limit to versus instead of here?

Sorry for adding more work, I do appreciate your contribution here. I can do the work of moving it over to versus if you prefer. :)

If you feel strongly that ethspam should have its own rate limiting feature, I am willing to merge this. I'm mostly reluctant in case it misleads people in how it should be used, plus there's already a lot of stdin rate limiting tooling that exists which ethspam can be piped through ([`pv`](https://linux.die.net/man/1/pv), [`rl`](https://github.com/42wim/rl), many others).

2020-04-05 16:56 UTC, shazow commented
Upon further contemplating, I think you're right, it would be good to have this native in ethspam. I can imagine cases where you want a specific cadence of input and to see how the endpoint holds up under steady flow. Let's do this!

Thanks again. :)

2020-04-05 16:57 UTC, merged